### ISSUE TITLE
GIT_LOCAL_DEVOPS_DEFAULT_CWD that devs can place in .bashrc export

### ISSUE THREAD

**Issue by firecow** [cego/git-local-devops#14]

**Comment by LauJosefsen** [comment]
So the logic should be, if the env "GIT_LOCAL_DEVOPS_DEFAULT_CWD" is set, then that is the cwd no matter where you call git-local-devops from?

Should there be an option to overwrite the env? Something like `git-local-devops up firecow.dk --use-cwd`

**Comment by firecow** [comment]
If no .git-local-devops.yml is found in the current location, it will fallback to GIT_LOCAL_DEVOPS_DEFAULT_CWD

**Comment by LauJosefsen** [comment]
Closing this issue, as it can be solved by simply creating an alias instead of the proposed env variable.
```gld_at_specific_dir="(cd ~/desired-folder && git-local-devops)"```

Will still solve for child directories via #29
